" .vimrc

" how many lines of history VIM needs to remember
set history=500

"use system clipboard
set clipboard=unnamedplus

" if using alacritty this helps with mouse support
set ttymouse=sgr

" required for ctrl-space
set hidden

" general mouse stuff
set mouse=a

" disable timeout for escape sequences
set timeoutlen=1000 ttimeoutlen=0

" filetype plugins
filetype plugin on
filetype indent on

" how many lines of history VIM needs to remember
set history=500

"use system clipboard
set clipboard=unnamedplus

" if using alacritty this helps with mouse support
set ttymouse=sgr

" general mouse stuff
set mouse=a

" disable timeout for escape sequences
set timeoutlen=1000 ttimeoutlen=0

" filetype plugins
filetype plugin on
filetype indent on

set runtimepath+=$XDG_CONFIG_HOME/vim/
set packpath+=$XDG_CONFIG_HOME/vim/
let g:dracula_colorterm = 0
packadd! dracula
packadd! nerdtree
packadd! nerdtree-git-plugin


colorscheme dracula

" this may improve the quality of colors or may make it worse, depends. But worth trying out
" set termguicolors

" autoread
set autoread

" sudo save file
command W w !sudo tee % > /dev/null

" something cursor and line related
set so=7

" ignore compiled files
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
  set wildignore+=.git\*,.hg\*,.svn\*
else
  set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" show current position and some line number / line stuff
set ruler
set number

" height of command bar
set cmdheight=1

" swap file
set noswapfile

" search stuff
set ignorecase
set smartcase

set hlsearch " highlight matches
set incsearch " search as characters are entered

" don't redraw while executing macros
set lazyredraw

" regex
set magic

" show matching brackets
set showmatch

" no bell sounds
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" enable syntax highlighting
syntax enable

if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif

" text, tab, indent related

set expandtab
set smarttab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set shiftwidth=2

" auto linebreak on 500 chars
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" status line
set statusline=\ %l:%c\ %{HasPaste()}%F%m%r%h\ %w\ %r%{getcwd()}%h

" editing mapping
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

nmap <A-q> :bp<CR>

map <C-Left> <Esc>:bprev<CR>
map <C-Right> <Esc>:bnext<CR>

" switch to left / right split (mostly for Nerd Tree)
map <C-h> <C-W>h
map <C-l> <C-W>l

" apparently fixes something with 
autocmd FileType nerdtree noremap <buffer> <A-q> <nop>

" nerdtree stuff
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsable = '▾'

let g:NERDTreeIndicatorMapCustom = {
  \ "Modified"  : "*",
  \ "Staged"    : "+",
  \ "Untracked" : "-",
  \ "Renamed"   : "➜",
  \ "Unmerged"  : "═",
  \ "Deleted"   : "✖",
  \ "Dirty"     : "✗",
  \ "Clean"     : "✔︎",
  \ "Ignored"   : "_",
  \ "Unknown"   : "?",
  \ }

let NERDTreeQuitOnOpen = 1

map <C-n> :NERDTreeToggle<CR>

" create new file in same directory as current file
" nmap <C-N> :wincmd w<CR>ma

" delete current file
" helper functions

function! HasPaste()
  if &paste
    return 'PASTE MODE  '
  endif
  return ''
endfunction
