" .vimrc

" disable dumb defaults
set backspace=indent,eol,start

" use system clipboard & os detection
if has("unix")
  let s:uname = system("uname -s")
  if s:uname == "Darwin\n"
    set clipboard=unnamed
  else
    set clipboard=unnamedplus
  endif
endif

" if using alacritty this helps with mouse support
set ttymouse=sgr

" required for ctrl-space
set hidden

" general mouse stuff
set mouse=a

" disable timeout for escape sequences
set timeoutlen=1000 ttimeoutlen=0

" splits open at the bottom and right, unlike vim defaults
set splitbelow splitright

" filetype plugins
filetype plugin on
filetype indent on

" how many lines of history VIM needs to remember
set history=500

set runtimepath+=$XDG_CONFIG_HOME/vim/
set packpath+=$XDG_CONFIG_HOME/vim/
let g:dracula_colorterm = 0
packadd! dracula
packadd! nerdtree
packadd! nerdtree-git-plugin

set rtp+=/usr/bin/fzf

function! MyHighlights() abort
  " I don't want to highlight the whole line, I only want the indicator in the line number column
  set cursorline
  highlight clear CursorLine
endfunction

augroup MyColors
  autocmd!
  autocmd ColorScheme * call MyHighlights()
augroup END

colorscheme paramount
"colorscheme dracula
set background=dark

" this may improve the quality of colors or may make it worse, depends. But worth trying out
" set termguicolors

let &t_8f="<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="<Esc>[48;2;%lu;%lu;$lum"

" autoread
set autoread

" sudo save file
command W w !sudo tee % > /dev/null

" something cursor and line related
set so=7

" ignore compiled files
set wildignore=*.o,*.so,*~,*.pyc
if has("win16") || has("win32")
  set wildignore+=.git\*,.hg\*,.svn\*
else
  set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store,*.swp
endif


" height of command bar
set cmdheight=1

" swap file
set noswapfile

" search stuff
set ignorecase
set smartcase

set hlsearch " highlight matches
set incsearch " search as characters are entered

" don't redraw while executing macros
set lazyredraw

" regex
set magic

" show matching brackets
set showmatch

" no bell sounds
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" enable syntax highlighting
syntax enable

if $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif

" text, tab, indent related

set expandtab
set smarttab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set shiftwidth=2

" auto linebreak on 500 chars
set lbr
set tw=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" show current position and some line number / line stuff
set ruler
set number
set relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
augroup END

set signcolumn=auto

" vim-markdown options
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_emphasis_multiline = 0
let g:vim_markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'ini=dosini']
let g:vim_markdown_follow_anchor = 1
let g:vim_markdown_math = 1
let g:vim_markdown_strikethrough = 1
let g:vim_markdown_new_list_item_indent = 2

" status line
set statusline=\ %l:%c\ %{HasPaste()}%F%m%r%h\ %w\ %r%{getcwd()}%h


" utility function
function! HasPaste()
  if &paste
    return 'PASTE MODE  '
  endif
  return ''
endfunction

let g:ycm_filetype_blacklist = {
            \ 'md': 1,
            \ }

" editing mapping
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" compatibility with mac os (custom) qwerty layout
nnoremap ö {
nnoremap ä }

" make d delete and not cut
nnoremap x "_x
nnoremap d "_d
nnoremap D "_D
vnoremap d "_d

nnoremap <silent> gc xph
nnoremap <silent> gC Xp

nnoremap <leader>d ""d
nnoremap <leader>D ""D
vnoremap <leader>d ""d

" toggle comments
nnoremap <C-7> <plug>NERDCommenterToggle
vnoremap <C-7> <plug>NERDCommenterToggle

" allow entering spaces when in normal mode
nnoremap <space> i<space><esc>
" don't go into insert mode when using o/O to insert newlines (notice that they are swapped)
nnoremap o O<esc>
nnoremap O o<esc>

" doesn't seem to work sadly (something related to alt key not being recognized correctly)
nmap <A-q> :bp<CR>

" switch between idek what they are, it's like backwards/forwards buttons
map <C-Left> <Esc>:bprev<CR>
map <C-Right> <Esc>:bnext<CR>

" switch to the next tab / the previous tab
map <C-Up> <Esc>:tabprev<CR>
map <C-Down> <Esc>:tabnext<CR>

" These shortcuts might seem like an anti-pattern as they use the arrow keys
" but these are actually intended to be used with a keyboard layout that
" maps the key right of the spacebar + hjkl to the arrow keys. This means
" that these shortcuts actually are really close to the ones below for different
" splits / panes as the only difference is additionally hitting the key right
" of the spacebar (this key is either right alt or right control depending on
" layout).


" switch to left / right / top / bottom split (mostly for Nerd Tree)
map <C-h> <C-W>h
map <C-l> <C-W>l
map <C-j> <C-W>j
map <C-k> <C-W>k

" apparently fixes something with
autocmd FileType nerdtree noremap <buffer> <A-q> <nop>

let g:gitgutter_async=1
let s:grep_available=0
let g:gitgutter_enabled = 1

" nerdcommenter stuff
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 0
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDToggleCheckAllLines = 1

" nerdtree stuff
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsable = '▾'

let g:NERDTreeIndicatorMapCustom = {
  \ "Modified"  : "*",
  \ "Staged"    : "+",
  \ "Untracked" : "-",
  \ "Renamed"   : "➜",
  \ "Unmerged"  : "═",
  \ "Deleted"   : "✖",
  \ "Dirty"     : "x",
  \ "Clean"     : "✔︎",
  \ "Ignored"   : "_",
  \ "Unknown"   : "?",
  \ }

let g:NERDTreeIgnore = ['^node_modules$']
let g:NERDTreeRespectWildIgnore = 1

let NERDTreeQuitOnOpen = 1

map <C-p> :NERDTreeToggle<CR>

" create new file in same directory as current file
" nmap <C-N> :wincmd w<CR>ma

" delete current file
" helper functions

" airline stuff
let g:airline_theme = 'minimalist'" 'dracula'
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#branch#enabled = 1
let g:airline_section_y = ''

let g:airline_mode_map = {
  \ 'n': 'normal',
  \ 'no': 'n·op pending',
  \ 'v': 'visual',
  \ 'V': 'v·line',
  \ '': 'v·block',
  \ 's': 'select',
  \ 'S': 's·line',
  \ '': 's·block',
  \ 'i': 'insert',
  \ 'R': 'replace',
  \ 'Rv': 'v·replace',
  \ 'c': 'command',
  \ 'cv': 'idk (cv)',
  \ 'ce': 'idk (ce)',
  \ 'r': 'prompt',
  \ 'rm': 'more',
  \ 'r?': 'confirm',
  \ '!': 'shell',
  \ 't': 'terminal',
  \ }

" https://stackoverflow.com/questions/6453595/prevent-vim-from-clearing-the-clipboard-on-exit
" xorg only stores a pointer to the clipboard data that resides in the program itself, meaning that
" after quitting this pointer is no longer usable, that is why after quitting applications the
" clipboard gets reset if the contents of teh clipboard belonged to the specific application.
" This should fix this atleast for vim by manually copying the "+" register directly into the clipboard.
autocmd VimLeave * call system("xsel -ib", getreg('+'))
