#!/bin/bash

# Example for ~/.config/sxiv/exec/image-info
# Called by nsxiv(1) whenever an image gets loaded,
# with the name of the image file as its first argument.
# The output is displayed in nsxiv's status bar.

s=" | " # field separator

path="$(realpath $1)"
width=$2
height=$3

dir="$(echo $path | sed "s|$HOME|~|")"

echo "${dir}${s}${width}x${height}"

