#!/bin/sh

create_notification() {
  dunstify --appname="awesomewm" --icon="$HOME/scripts/assets/clipboard.svg" $1 &
}

while read file; do

  # nsxiv prepends the path with multiple slashes for some reason
  path="$(realpath $file)"
  filename="$(basename $file)"

  case "$1" in
    "y")
      echo -n "$path" | xclip -selection clipboard &&
        create_notification "\"$path\" copied" ;;
    "C-y")
      echo -n "$filename" | xclip -selection clipboard &&
        create_notification "\"$filename\" copied" ;;
    "Y")
      xclip -selection clipboard -target image/png -i "$path" &&
        create_notification "copied image to clipboard ($filename)" ;;
  esac

done
