#!/usr/bin/env sh

# taken from:
#
# This script allows piping images into nsxiv via draining the pipe into a temp file. The reason for this is because Imlib2 (the image library nsxiv uses) cannot read from pipes ([#32](https://github.com/nsxiv/nsxiv/issues/32#issuecomment-957224839)). $TMPDIR is respected if set.
#
# Example usage:
# ```sh
# curl 'https://link.to/image' | nsxiv-pipe
# nsxiv-pipe < /path/to/image.png
# ```
#
# Authors:
# - mamg22 marcomonizg@gmail.com
# - NRK <nrk at disroot dot org>

tmpfile="${TMPDIR:-/tmp}/nsxiv-pipe-$$"

trap 'rm -f -- $tmpfile' EXIT

if [ "$#" -eq 0 ]; then
    if [ -t 0 ]; then
        echo "nsxiv-pipe: No arguments provided" >&2; exit 1
    else
        # Consume stdin and put it in the temporal file
        cat > "$tmpfile"
    fi
fi

for arg in "$@"; do
    # if it's a pipe then drain it to $tmpfile
    [ -p "$arg" ] && cat "$arg" > "$tmpfile"
done

if [ -s "$tmpfile" ]; then
    nsxiv -q "$@" "$tmpfile" # -q to silence warnings
else
    nsxiv "$@" # fallback
fi
