#!/usr/bin/env sh

# taken from: https://github.com/nsxiv/nsxiv-extra/blob/master/scripts/nsxiv-rifle/nsxiv-rifle
#
# This is a modified version of the sxiv-rifle script. This script opens an image as well as all the other images in that directory.
#
# Authors:
# - Original sxiv-rifle authors
# - NRK <nrk at disroot dot org>

tmp="/tmp/nsxiv_rifle_$$"

listfiles() {
  find -L "///${1%/*}" -maxdepth 1 -type f -print |
    grep -iE '\.(jpe?g|png|gif|webp|tiff|bmp|avif|heif)$' |
    sort | tee "$tmp"
}

is_img() {
  case "${1##*.}" in
    "jpg"|"jpeg"|"png"|"gif"|"webp"|"tiff"|"bmp"|"avif"|"heif") return 0 ;;
    "JPG"|"JPEG"|"PNG"|"GIF"|"WEBP"|"TIFF"|"BMP"|"AVIF"|"HEIF") return 0 ;;
    *)
      echo "unsupported file format: ${1##*.}"
      return 1 ;;
  esac
}

open_img() {
  is_img "$1" || exit 1
  trap 'rm -f $tmp' EXIT
  count="$(listfiles "$1" | grep -nF "$1")"
  if [ -n "$count" ]; then
    nsxiv -i -n "${count%%:*}" -- < "$tmp"
  else
    nsxiv -- "$@" # fallback
  fi
}

[ "$1" = '--' ] && shift
case "$1" in
  "") echo "Usage: ${0##*/} PICTURES" >&2; exit 1 ;;
  /*) open_img "$1" ;;
  "~"/*) open_img "$HOME/${1#"~"/}" ;;
  *) open_img "$PWD/$1" ;;
esac
