#!/usr/bin/env sh

raw_colors="$(colorpicker --one-shot --preview)"
colors="$(echo $raw_colors| grep -Po ':\s+#?(\d|[a-fA-F])+' | grep -Po '#?(\d|[a-fA-F])+')"

array=(${colors//$'\n'/ })
r=${array[0]}
g=${array[1]}
b=${array[2]}
hex=${array[3]}
hsl=$(rgb2hsl $hex)


# modify this to fit your needs
full_text=$(
  echo "hex: $hex" &&
  echo "r: $r, g: $g b: $b"
  echo "$hsl"
)

bgcolor=${hex}
lightness=$(echo $hsl | grep -Po 'l: \d+' | grep -Po '\d+')
[[ $lightness -ge 70 ]] && fgcolor="#000000" || fgcolor="#ffffff"

# for debugging purposes
# echo $raw_colors
# echo $colors
# echo $hsl
#echo $bgcolor
#echo $fgcolor

# copy hex color to clipboard
echo $hex | xclip -sel clip

# send notification (using hex color as background color and without using an icon)
notify-send \
  -h "string:bgcolor:${bgcolor}" \
  -h "string:fgcolor:${fgcolor}" \
  -i "/dev/null" \
  -a "pick-color" \
  "${full_text}"

