#!/usr/bin/env sh

if ! command -v colorpicker &> /dev/null; then
  echo "colorpicker not installed, available on the AUR (https://aur.archlinux.org/packages/colorpicker/)"
  exit
fi

LOGFILE="$XDG_CONFIG_HOME/pick-color/recent"
LOGFILETMP="$XDG_CONFIG_HOME/pick-color/recent-tmp"
LOGCOUNT=10

log_to_recents() {
  echo $1 >> $LOGFILE
  cat $LOGFILE | awk '!x[$0]++' | tail -n $LOGCOUNT > $LOGFILETMP
  mv $LOGFILETMP $LOGFILE
}

# i prefer lowercase hex numbers
[[ "$#" -eq 0 ]] && hex="$(colorpicker --one-shot --short --preview)" || hex=$1
hex=$(echo $hex | tr '[:upper:]' '[:lower:]')
r=$(printf "%d" 0x${hex:1:2})
g=$(printf "%d" 0x${hex:3:2})
b=$(printf "%d" 0x${hex:5:2})

hsl=$(rgb2hsl --short $hex)
hsl_array=(${hsl//$' '/ })
h=${hsl_array[0]}
s=${hsl_array[1]}
l=${hsl_array[2]}

# modify this to fit your needs
full_text=$(
  echo "hex: $hex" &&
  echo "r: $r, g: $g b: $b"
  echo "h: ${h}deg, s: ${s}%, l: ${l}%"
)

darken() {
  local v=15 # value to subtract from l
  local h=$1
  local s=$2
  local l=$(( $3 < $v ? 0 : $3 - $v))

  echo $(hsl2rgb --hex $h $s $l)
}

lighten() {
  local v=15 # value to add to l
  local h=$1
  local s=$2
  local l=$(( $3 > 100 - $v ? 100 : $3 + $v))

  echo $(hsl2rgb --hex $h $s $l)
}


bgcolor=${hex}
[[ $l -ge 70 ]] && fgcolor="#000000" || fgcolor="#ffffff"
[[ $l -ge 50 ]] && frcolor=$(darken $h $s $l) || frcolor=$(lighten $h $s $l)

# for debugging purposes
# echo $h $s $l
# echo bg $bgcolor
# echo fg $fgcolor
# echo fr $frcolor

# copy hex color to clipboard
echo $hex | xclip -sel clip

[[ "$#" -eq 0 ]] && log_to_recents $hex

# send notification (using hex color as background color and without using an icon)
notify-send \
  -h "string:bgcolor:${bgcolor}" \
  -h "string:fgcolor:${fgcolor}" \
  -h "string:frcolor:${frcolor}" \
  -i "/dev/null" \
  -a "pick-color" \
  "${full_text}"

