#!/bin/sh
DIR=${1:-~}
while [ ! -f "$DIR" ]; do
    NEWDIR="$(ls -1  "$DIR" | rofi -dmenu -i -p "file" -l 20)"
    if [ -z "$NEWDIR" ]; then
        exit;
    fi
    DIR="$(readlink -f "$DIR/$NEWDIR")"
done
echo "$DIR"
