#!/usr/bin/env sh

SHOW_NOTIF=[ "$1" == "--show-notification" ] && "1" || "0"

function show_notif() {
  dunstify --appname "kdeconnect" -i $HOME/scripts/smartphone.svg "$1"
}

# id of phone, may need to adjust this if multiple phones are connected
ID=$(kdeconnect-cli --list-available --id-only)
TMPFILE=/tmp/kde-connect-$(date +"%Y_%m_%d_%I_%M_%p").jpg

# send phone command to take photo
kdeconnect-cli -d $ID --photo $TMPFILE
# previous command finishes directly after sending the command to the phone
# this will wait until the photo has been saved before proceeding
while [ ! -f $TMPFILE ]
do
  sleep 0.1
done
# convert image to png and save it to the clipboard
convert "${TMPFILE}" png:- | xclip -sel clip -t image/png
rm $TMPFILE

if [[ $SHOW_NOTIF = true ]]; then
  show_notif "scanned image from phone; copied"
fi

exit 0
