#!/usr/bin/env bash

command -v latex > /dev/null 2>&1 || {
  echo "$(tput bold)$(tput setaf 1)latex required$(tput sgr0)"
  exit 1 
}

command -v dvisvgm > /dev/null 2>&1 || {
  echo "$(tput bold)$(tput setaf 1)dvisvgm required$(tput sgr0) (dvisvgm.de/Downloads; see https://gist.github.com/tobywf/aeeeee63053aaaa841b4032963406684 for possible problems with kpathsea)$(tput sgr0)"
  exit 1
}

[[ ! -f "$1" ]] && {
  echo "$(tput bold)$(tput setaf 1)file \"$1\" does not exist$(tput sgr0)"
  exit 1
}

no_ending=$(echo $1 | sed "s/.tex//")

latex --interaction=nonstopmode $1 &> "tex2svg-${no_ending}.log" && dvisvgm "${no_ending}.dvi" >/dev/null 2>&1 && {
  rm "${no_ending}.dvi"
  rm "tex2svg-${no_ending}.log" # nothing went wrong, can delete self generated log file now
  echo "$(tput bold)$(tput setaf 2)Successfully parsed file \"${no_ending}.tex\"$(tput sgr0)"
} || {
  echo "$(tput bold)$(tput setaf 1)Error in file \"${no_ending}.tex\"$(tput sgr0)"
}

rm "${no_ending}.aux" # remove as these are also generated when an error occurs
rm "${no_ending}.log" # the tex2svg-<file>.log file already contains the errors
